version: 2

build:
  image: latest

python:
  version: '3.8'
  install: # do I need any of this if I have the conda environment
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
            - docs

conda:
  environment: environment.yml

sphinx:
  configuration:
    docs/conf.py
