name: napari_image_similarity_search
dependencies:
  - python
  - pip
  - pip:
      - napari
      - matplotlib
      - numpy
      - Pillow
      - umap-learn
      - PyQt5
      - qtpy
      - napari-image-similarity-search